# Generated by Django 6.0 on 2026-01-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acad_ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
    ]
