# Generated by Django 6.0 on 2026-01-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acad_ai_app', '0004_alter_question_options_exam_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, help_text='Applicable for MCQ type questions. Provide choices as a JSON array of strings.', null=True),
        ),
    ]
