# Generated by Django 6.0 on 2026-01-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acad_ai_app', '0005_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='percentage',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('grading', 'Grading'), ('graded', 'Graded')], db_index=True, default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code', 'name'], name='Acad_ai_app_code_0ef605_idx'), models.Index(fields=['-created_at'], name='Acad_ai_app_created_a7c9a3_idx')],
            },
        ),
    ]
