# Generated by Django 6.0 on 2026-01-04 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acad_ai_app', '0006_submission_feedback_submission_passed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Acad_ai_app.course'),
        ),
    ]
