# Generated by Django 6.0 on 2026-01-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acad_ai_app', '0007_alter_exam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='min_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
