# Generated by Django 6.0 on 2026-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acad_ai_app', '0008_submission_min_word_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='min_word_count',
        ),
        migrations.AddField(
            model_name='question',
            name='min_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
