# Generated by Django 6.0 on 2026-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acad_ai_app', '0009_remove_submission_min_word_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
