# Generated by Django 6.0 on 2026-01-05 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acad_ai_app', '0010_question_keywords'),
        ('course_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='Acad_ai_app_code_0ef605_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='Acad_ai_app_created_a7c9a3_idx',
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course_module.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
